/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasAkhir;

import static TugasAkhir.DataKaryawan.a;
import java.io.File;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import javazoom.jl.player.Player;
import static sun.misc.PostVMInitHook.run;
import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author herib
 */
public class Aplikasi extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    static String a,b,c;

    public Aplikasi() {
        initComponents();
        play();
        run();
        ActionListener acl=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                a = selamatdatang.getText();
                b = a.substring(0,1);
                c = a.substring(1, a.length());
                selamatdatang.setText(c+b);
            }
        };new javax.swing.Timer(300, acl).start();
    }

    private static String filename;
    static Player player;
    public static void play() {
        try {
            FileInputStream fis     = new FileInputStream("src\\mp3\\Mars Korpri - Lirik Lagu Nasional Indonesia.mp3");
            BufferedInputStream bis = new BufferedInputStream(fis);
            player = new Player(bis);
        }
        catch (Exception e) {
            System.out.println("Problem playing file " + filename);
            System.out.println(e);
        }

        // memutar musik menjadi background
        new Thread() {
            @Override
            public void run() {
                try {player.play();
                }
                catch (Exception e) { System.out.println(e); }
            }
        }.start();
    }
    public void close()
       {
           player.close();
       }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2tutup = new javax.swing.JButton();
        jButton2Close1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        menujuabout = new javax.swing.JButton();
        CDC = new javax.swing.JButton();
        CDA = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menujuabsensi = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menujucuti = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(799, 620));
        setUndecorated(true);
        setSize(new java.awt.Dimension(799, 620));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(799, 32767));
        jPanel1.setPreferredSize(new java.awt.Dimension(779, 72));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Home");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 13, 47, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("APLIKASI ABSENSI PEGAWAI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 10, 520, 42);

        jButton2tutup.setBackground(new java.awt.Color(255, 0, 0));
        jButton2tutup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2tutup.setText("-");
        jButton2tutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2tutupMouseClicked(evt);
            }
        });
        jButton2tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2tutupActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2tutup);
        jButton2tutup.setBounds(700, 0, 50, 40);

        jButton2Close1.setBackground(new java.awt.Color(255, 0, 0));
        jButton2Close1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2Close1.setText("X");
        jButton2Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2Close1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2Close1);
        jButton2Close1.setBounds(750, 0, 50, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 60);

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(255, 255, 0));
        jPanel11.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\Tidak berjudul.png")); // NOI18N
        jPanel11.add(jLabel7);
        jLabel7.setBounds(40, 10, 90, 80);

        menujuabout.setBackground(new java.awt.Color(255, 153, 51));
        menujuabout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menujuabout.setText("ABOUT");
        menujuabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menujuaboutActionPerformed(evt);
            }
        });
        jPanel11.add(menujuabout);
        menujuabout.setBounds(30, 90, 100, 25);

        jPanel2.add(jPanel11);
        jPanel11.setBounds(540, 270, 160, 150);

        CDC.setBackground(new java.awt.Color(0, 204, 204));
        CDC.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CDC.setText("CETAK DATA CUTI");
        CDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDCActionPerformed(evt);
            }
        });
        jPanel2.add(CDC);
        CDC.setBounds(20, 330, 170, 23);

        CDA.setBackground(new java.awt.Color(0, 204, 204));
        CDA.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        CDA.setText("CETAK DATA ABSENSI");
        CDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDAActionPerformed(evt);
            }
        });
        jPanel2.add(CDA);
        CDA.setBounds(20, 300, 170, 25);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton1.setText("DATA KARYAWAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 260, 170, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\add2.png")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 100, 50, 60);

        jPanel9.setBackground(new java.awt.Color(255, 255, 0));
        jPanel9.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\iconjadwal.png")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(40, 30, 80, 60);

        menujuabsensi.setBackground(new java.awt.Color(255, 153, 51));
        menujuabsensi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menujuabsensi.setText("ABSENSI");
        menujuabsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menujuabsensiActionPerformed(evt);
            }
        });
        jPanel9.add(menujuabsensi);
        menujuabsensi.setBounds(30, 100, 100, 25);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(320, 70, 160, 150);

        jPanel10.setBackground(new java.awt.Color(255, 255, 0));
        jPanel10.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\iconcuti.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(40, 20, 110, 70);

        menujucuti.setBackground(new java.awt.Color(255, 153, 51));
        menujucuti.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menujucuti.setText("CUTI");
        menujucuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menujucutiActionPerformed(evt);
            }
        });
        jPanel10.add(menujucuti);
        menujucuti.setBounds(30, 100, 100, 25);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(540, 70, 160, 150);

        jPanel8.setBackground(new java.awt.Color(255, 255, 0));
        jPanel8.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\iconlogout.png")); // NOI18N
        jPanel8.add(jLabel6);
        jLabel6.setBounds(50, 10, 80, 70);

        kembali.setBackground(new java.awt.Color(255, 153, 51));
        kembali.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kembali.setText("LOG OUT");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel8.add(kembali);
        kembali.setBounds(30, 90, 100, 25);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(320, 270, 160, 150);

        x1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        x1.setForeground(new java.awt.Color(255, 0, 0));
        x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(x1);
        x1.setBounds(20, 160, 170, 30);

        y1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        y1.setForeground(new java.awt.Color(255, 0, 0));
        y1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(y1);
        y1.setBounds(21, 200, 170, 30);

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jPanel3);
        jPanel3.setBounds(230, 0, 20, 560);

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setLayout(null);

        selamatdatang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel4.add(selamatdatang);
        selamatdatang.setBounds(0, 0, 860, 60);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(250, 0, 550, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 800, 560);

        setSize(new java.awt.Dimension(799, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2tutupMouseClicked
        this.setState(JFrame.ICONIFIED);
        close();
    }//GEN-LAST:event_jButton2tutupMouseClicked

    private void jButton2Close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2Close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton2Close1MouseClicked

    private void jButton2tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2tutupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2tutupActionPerformed

    private void menujuaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menujuaboutActionPerformed
        close();
        About a;
        a = new About();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menujuaboutActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        close();
        Login lg;
        lg = new Login();
        lg.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_kembaliActionPerformed

    private void menujucutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menujucutiActionPerformed
        close();
        CutiForm cc;
        cc = new CutiForm();
        cc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menujucutiActionPerformed

    private void menujuabsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menujuabsensiActionPerformed
        close();
        InOut ab;
        ab = new InOut();
        ab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menujuabsensiActionPerformed

    private void CDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDAActionPerformed
        try{
            File name = new File("src/TugasAkhir/laporan/laporan_absensi.jasper");
            JasperPrint jp = JasperFillManager.fillReport(name.getPath(), null, (Connection) AbsensiPegawai.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_CDAActionPerformed

    private void CDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDCActionPerformed
        try{
            File name = new File("src/TugasAkhir/laporan/laporan_cuti.jasper");
            JasperPrint jp = JasperFillManager.fillReport(name.getPath(), null, (Connection) AbsensiPegawai.getConnection());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_CDCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        DataKaryawan ab;
        ab = new DataKaryawan();
        ab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Aplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CDA;
    private javax.swing.JButton CDC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2Close1;
    private javax.swing.JButton jButton2tutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton kembali;
    private javax.swing.JButton menujuabout;
    private javax.swing.JButton menujuabsensi;
    private javax.swing.JButton menujucuti;
    public static final javax.swing.JLabel selamatdatang = new javax.swing.JLabel();
    public static final javax.swing.JLabel x1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel y1 = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
