/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasAkhir;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author herib
 */
public class AttendanceForm extends javax.swing.JFrame {
    int xMouse;
    int yMouse;

    public AttendanceForm() {
        initComponents();
    }
    private DefaultTableModel tabmode;
    private void Kosongkan_Form(){
        InputNIP.setEditable(true);
        InputNIP.setText(null);
        AtNama.setText(null);
        AtJabatan.setText(null);
        InTime1.setText(null);
        OutTime.setText(null);
        attanggal.setText(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Attendance = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AtNama = new javax.swing.JTextField();
        AtJabatan = new javax.swing.JTextField();
        attanggal = new javax.swing.JTextField();
        jButton1simpan = new javax.swing.JButton();
        jButton2edit = new javax.swing.JButton();
        jButton3hapus = new javax.swing.JButton();
        jButton4batal = new javax.swing.JButton();
        jButton5keluar = new javax.swing.JButton();
        OutTime = new javax.swing.JTextField();
        InTime1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InputNIP = new javax.swing.JTextField();
        tampilkan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(799, 620));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable1Attendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama", "Jabatan", "InTime", "OutTime", "Date"
            }
        ));
        jTable1Attendance.setMaximumSize(new java.awt.Dimension(1345, 619));
        jTable1Attendance.setMinimumSize(new java.awt.Dimension(1345, 619));
        jTable1Attendance.setPreferredSize(new java.awt.Dimension(1345, 619));
        jTable1Attendance.setRequestFocusEnabled(false);
        jTable1Attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1AttendanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Attendance);
        if (jTable1Attendance.getColumnModel().getColumnCount() > 0) {
            jTable1Attendance.getColumnModel().getColumn(0).setResizable(false);
            jTable1Attendance.getColumnModel().getColumn(1).setResizable(false);
            jTable1Attendance.getColumnModel().getColumn(2).setResizable(false);
            jTable1Attendance.getColumnModel().getColumn(3).setResizable(false);
            jTable1Attendance.getColumnModel().getColumn(4).setResizable(false);
            jTable1Attendance.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 330, 800, 230);

        jLabel1.setText("Nama    :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 60, 30);

        jLabel2.setText("Jabatan  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 60, 30);

        jLabel3.setText("In Time   :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 70, 30);

        jLabel4.setText("Out Time :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 160, 70, 30);

        jLabel5.setText("Date      :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 200, 60, 30);
        getContentPane().add(AtNama);
        AtNama.setBounds(100, 40, 230, 30);
        getContentPane().add(AtJabatan);
        AtJabatan.setBounds(100, 80, 230, 30);
        getContentPane().add(attanggal);
        attanggal.setBounds(100, 200, 230, 30);

        jButton1simpan.setText("SIMPAN");
        jButton1simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1simpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1simpan);
        jButton1simpan.setBounds(70, 260, 80, 40);

        jButton2edit.setText("EDIT");
        jButton2edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2editMouseClicked(evt);
            }
        });
        jButton2edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2editActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2edit);
        jButton2edit.setBounds(170, 260, 80, 40);

        jButton3hapus.setText("HAPUS");
        jButton3hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3hapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3hapus);
        jButton3hapus.setBounds(270, 260, 80, 40);

        jButton4batal.setText("BATAL");
        jButton4batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4batalActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4batal);
        jButton4batal.setBounds(370, 260, 80, 40);

        jButton5keluar.setText("KELUAR");
        jButton5keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5keluarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5keluar);
        jButton5keluar.setBounds(470, 260, 90, 40);
        getContentPane().add(OutTime);
        OutTime.setBounds(100, 160, 230, 30);

        InTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InTime1ActionPerformed(evt);
            }
        });
        getContentPane().add(InTime1);
        InTime1.setBounds(100, 120, 230, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Inputkan NIP");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 50, 90, 17);
        getContentPane().add(InputNIP);
        InputNIP.setBounds(580, 80, 120, 30);

        tampilkan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tampilkan.setText("Refresh Table");
        tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanActionPerformed(evt);
            }
        });
        getContentPane().add(tampilkan);
        tampilkan.setBounds(330, 570, 140, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\Attendance.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 800, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1simpanActionPerformed
        Attendance a = new Attendance(InTime1.getText(), OutTime.getText(), attanggal.getText(), InputNIP.getText(), AtNama.getText(), AtJabatan.getText());
        String masuk = a.getIT();
        String pulang = a.getOT();
        String date = a.getDT();
        String nip = a.getNP();
        String nama = a.getNM();
        String jabatan = a.getJBTN();
        try{
            String sql = " INSERT INTO attendance VALUES('"+ nip + "','" + nama + "','" + jabatan + "','" + masuk + "','" + pulang + "','" + date+ "')";
            java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil");
        } catch (HeadlessException |SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        DefaultTableModel model = (DefaultTableModel) jTable1Attendance.getModel();        
        model.addRow(new Object[]{nip,nama,jabatan,masuk,pulang,date});
    }//GEN-LAST:event_jButton1simpanActionPerformed

    private void jTable1AttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1AttendanceMouseClicked
        int row = jTable1Attendance.getSelectedRow();
        InputNIP.setText(jTable1Attendance.getModel().getValueAt(row, 0).toString());
        AtNama.setText(jTable1Attendance.getModel().getValueAt(row, 1).toString());
        AtJabatan.setText(jTable1Attendance.getModel().getValueAt(row, 2).toString());
        InTime1.setText(jTable1Attendance.getModel().getValueAt(row, 3).toString());
        OutTime.setText(jTable1Attendance.getModel().getValueAt(row, 4).toString());
        attanggal.setText(jTable1Attendance.getModel().getValueAt(row, 5).toString());
        
        jButton2edit.setEnabled(true);
        jButton3hapus.setEnabled(true);
        jButton4batal.setEnabled(false);     
        jButton5keluar.setEnabled(true); 
    }//GEN-LAST:event_jTable1AttendanceMouseClicked

    private void InTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InTime1ActionPerformed

    private void jButton2editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2editMouseClicked
        
    }//GEN-LAST:event_jButton2editMouseClicked

    private void jButton2editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2editActionPerformed
        AbsensiMasuk a = new AbsensiMasuk(InTime1.getText(), OutTime.getText(), attanggal.getText(), InputNIP.getText(), AtNama.getText(), AtJabatan.getText());
        String masuk = a.getIT();
        String pulang = a.getOT();
        String date = a.getDT();
        String nip = a.getNP();
        String nama = a.getNM();
        String jabatan = a.getJBTN();
        try{
            String sql = "INSERT attendance set NIP = '"+nip+"' , Nama = '"+nama+"' ,Jabatan = '"+jabatan+"' , InTime = '"+masuk+"' ,OutTime = '"+pulang+"' ,Date = '"+date+"' On Duplicate Key Update NIP = '"+nip+"' , Nama = '"+nama+"' ,Jabatan = '"+jabatan+"' , InTime = '"+masuk+"' ,OutTime = '"+pulang+"' ,Date = '"+date+"'";
            java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Edit Data Berhasil...");
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2editActionPerformed

    private void jButton4batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4batalActionPerformed
        Kosongkan_Form();
    }//GEN-LAST:event_jButton4batalActionPerformed

    private void jButton3hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3hapusActionPerformed
        try{
            String sql = "DELETE FROM attendance WHERE NIP='" + InputNIP.getText() + "'";
                    java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.execute();
                    JOptionPane.showMessageDialog(null, "Hapus Data Berhasil...");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Kosongkan_Form();
    }//GEN-LAST:event_jButton3hapusActionPerformed

    private void tampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanActionPerformed
        Object[]baris = {"NIP", "Nama", "Jabatan", "InTime", "OutTime", "Date"};
        tabmode = new DefaultTableModel(null, baris);
        jTable1Attendance.setModel(tabmode);
        try{
            String sql = "SELECT * FROM `attendance` order by NIP asc ";
            java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            ResultSet hasil = pstm.executeQuery(sql);
            while (hasil.next()){
                String nip = hasil.getString("NIP");
                String nama = hasil.getString("Nama");
                String jbtn = hasil.getString("Jabatan");
                String it = hasil.getString("InTime");
                String ot = hasil.getString("OutTime");
                String tgl = hasil.getString("Date");
                String[] data = {nip, nama,jbtn, it, ot, tgl};
                tabmode.addRow(data);
            }
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tampilkanActionPerformed

    private void jButton5keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5keluarActionPerformed
        Aplikasi xx;
        xx = new Aplikasi();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5keluarActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed
    public static void AddRowJTable(Object[] dataRow){
        DefaultTableModel model = (DefaultTableModel)jTable1Attendance.getModel();
        model.addRow(dataRow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AtJabatan;
    private javax.swing.JTextField AtNama;
    private javax.swing.JTextField InTime1;
    private javax.swing.JTextField InputNIP;
    private javax.swing.JTextField OutTime;
    private javax.swing.JTextField attanggal;
    private javax.swing.JButton jButton1simpan;
    private javax.swing.JButton jButton2edit;
    private javax.swing.JButton jButton3hapus;
    private javax.swing.JButton jButton4batal;
    private javax.swing.JButton jButton5keluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1Attendance;
    private javax.swing.JButton tampilkan;
    // End of variables declaration//GEN-END:variables
}
