/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasAkhir;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author herib
 */
public class CreatForm extends javax.swing.JFrame {
    int xMouse;
    int yMouse;

    /**
     * Creates new form Creat
     */

    
    public CreatForm() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    public void hapuslayar(){
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }
    public void kosongkan(){
        txtNama.setText("");
        txtNIP.setText("");
        txtalamat.setText("");
        txtemail.setText("");
        txtjabatan.setText("");
        txtnotelp.setText("");
        txttgl.setDateFormatString("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        txtnotelp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txttgl = new com.toedter.calendar.JDateChooser();
        Back = new javax.swing.JButton();
        creat1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        salah = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtNIP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 560));
        setMinimumSize(new java.awt.Dimension(550, 560));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 7, 246));
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(725, 566));
        jPanel2.setMinimumSize(new java.awt.Dimension(725, 566));
        jPanel2.setPreferredSize(new java.awt.Dimension(725, 566));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel1.setText("Register");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(1876, 0, 104, 49);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel10.setText("REGISTER");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(12, 9, 132, 31);

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close);
        close.setBounds(490, 0, 60, 60);

        minimize.setBackground(new java.awt.Color(255, 0, 0));
        minimize.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(minimize);
        minimize.setBounds(430, 0, 60, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 550, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nama                :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 110, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Jabatan             :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 140, 110, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Email                :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 240, 110, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ketik Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 320, 110, 16);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("No. Telepon       :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 360, 110, 16);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Alamat              :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 400, 110, 16);
        getContentPane().add(txtalamat);
        txtalamat.setBounds(150, 400, 290, 70);
        getContentPane().add(txtNama);
        txtNama.setBounds(150, 90, 290, 30);
        getContentPane().add(txtjabatan);
        txtjabatan.setBounds(150, 130, 290, 30);

        txtnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotelpActionPerformed(evt);
            }
        });
        getContentPane().add(txtnotelp);
        txtnotelp.setBounds(150, 360, 290, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Tanggal Lahir   :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 190, 110, 16);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail);
        txtemail.setBounds(150, 240, 290, 30);

        txttgl.setDateFormatString("dd MMMM yyyy");
        getContentPane().add(txttgl);
        txttgl.setBounds(150, 190, 180, 30);

        Back.setBackground(new java.awt.Color(255, 51, 51));
        Back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(150, 510, 110, 30);

        creat1.setBackground(new java.awt.Color(51, 153, 255));
        creat1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        creat1.setText("CREAT");
        creat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creat1MouseClicked(evt);
            }
        });
        creat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creat1ActionPerformed(evt);
            }
        });
        getContentPane().add(creat1);
        creat1.setBounds(330, 510, 110, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Password           :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 280, 110, 16);

        salah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salah.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(salah);
        salah.setBounds(150, 470, 290, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(150, 280, 290, 30);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(150, 320, 290, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("NIP  :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 190, 36, 17);

        txtNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIPActionPerformed(evt);
            }
        });
        getContentPane().add(txtNIP);
        txtNIP.setBounds(400, 190, 100, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasAkhir/images/create.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-410, 60, 960, 500);

        setSize(new java.awt.Dimension(550, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotelpActionPerformed

    private void creat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creat1ActionPerformed

        Creat a = new Creat() {};
        String dnkosong = a.getNMS();
        String djkosong = a.getJBTNS();
        String npkosong = a.getNPS();
        String dekosong = a.getEMLS();
        String dpkosong = a.getPASSS();
        String drkosong = a.getREPASSS();
        String dntkosong = a.getTLPS();
        String dakosong = a.getALMTS();
        Creat b = new Creat(txtNama.getText(),txtjabatan.getText(),null,txtNIP.getText(),txtemail.getText(),String.valueOf(jPasswordField1.getPassword()),String.valueOf(jPasswordField2.getPassword()),txtnotelp.getText(),txtalamat.getText()) {};
        String nama = b.getNM();
        String jabatan = b.getJBTN();
        String nip = b.getNP();
        String email = b.getEML();
        String password = b.getPASS();
        String repass = b.getALMT();
        String notelp = b.getTLP();
        String bdate = b.getTgl();    
        String alamat = b.getALMT();
        
        if(jPasswordField1.getText() == null ? jPasswordField2.getText() != null : !jPasswordField1.getText().equals(jPasswordField2.getText())){
            salah.setText("Password Yang Anda Masukkan Tidak Sama");
            hapuslayar();  
        }
        else if(nama.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan Nama");
            salah.setText(dnkosong);
        }
        else if(jabatan.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan Jabatan");
            salah.setText(djkosong);
        }
        else if(nip.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan NIP Anda");
            salah.setText(npkosong);
        }
        else if(email.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan Email");
            salah.setText(dekosong);
        }
        else if(password.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Tambahkan Password");
            salah.setText(dpkosong);
        }
        else if(notelp.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan Nomor Telepon Anda");
            salah.setText(dntkosong);
        }
        else if(alamat.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan Alamat");
            salah.setText(dakosong);
        }
        else if(checkAccount(email)){
            JOptionPane.showMessageDialog(null, "Akun/Email Tersebut Telah Terdaftar");
        }
        else{ 
            if(txttgl.getDate() != null){
            SimpleDateFormat dateformat = new SimpleDateFormat("dd-MMMM-YYYY");
            bdate = dateformat.format(txttgl.getDate());
        }
        
        PreparedStatement ps;
        String query = "INSERT INTO `create`(`NIP`,`Nama`, `Jabatan`, `Tanggal_Lahir`, `Email`, `Password`, `No.Telepon`, `Alamat`) VALUES (?,?,?,?,?,?,?,?)";
        
        try {
            ps = AbsensiPegawai.getConnection().prepareStatement(query);
            
            ps.setString(1, nip);
            ps.setString(2, nama);
            ps.setString(3, jabatan);
            ps.setString(5, email);
            ps.setString(6, password);
            ps.setString(7, notelp);
            if(bdate != null)
            {
                ps.setString(4, bdate);
            }
            else{ps.setNull(4, 0);           
            }
            ps.setString(8, alamat);
            
            ps.executeUpdate();
            {
                JOptionPane.showMessageDialog(null, "Akun Berhasil Dibuat");  
            }
            kosongkan();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Akun Gagal Dibuat" +e);
        }
        }
    }//GEN-LAST:event_creat1ActionPerformed

    //Menampilkan apabila akun telah terdaftar
    public boolean checkAccount(String Account){
        PreparedStatement ps;
        ResultSet rs;
        boolean checkAccount = false;
        String query="SELECT * FROM `create` WHERE `Email` =?";
        try {
            ps = AbsensiPegawai.getConnection().prepareStatement(query);
            ps.setString(1, Account);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkAccount = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CreatForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkAccount;
    }
    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Login xx;
        xx = new Login();
        xx.setVisible(true);
        this.dispose();
        xx.setDefaultCloseOperation(CreatForm.EXIT_ON_CLOSE);
    }//GEN-LAST:event_BackActionPerformed

    private void creat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creat1MouseClicked

    }//GEN-LAST:event_creat1MouseClicked

    private void txtNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIPActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton close;
    private javax.swing.JButton creat1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JButton minimize;
    private javax.swing.JLabel salah;
    private javax.swing.JTextField txtNIP;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnotelp;
    private com.toedter.calendar.JDateChooser txttgl;
    // End of variables declaration//GEN-END:variables
}
