/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasAkhir;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author herib
 */
public class CutiForm extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    String a,b,c;

    /**
     * Creates new form Cuti
     */
    public CutiForm() {
        initComponents();
        tanggal();
        CNama.setEditable(false);
        tanggal.setEditable(false);
        Cdurasicuti.setEditable(false);
        Keterangan.setEditable(false);
        Submit.setEnabled(false);
        ActionListener acl=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                a = gerak.getText();
                b = a.substring(0,1);
                c = a.substring(1, a.length());
                gerak.setText(c+b);
            }
        };new javax.swing.Timer(300, acl).start();
        mcuti mc = new mcuti();
        mc.play();
    }
    
    public void tanggal(){
        java.util.Date Datenow = new java.util.Date();
        SimpleDateFormat smpdtfmt = new SimpleDateFormat("YYYY-MM-dd", Locale.getDefault());
        String tgl = smpdtfmt.format(Datenow);
        tanggal.setText(tgl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        CNip = new javax.swing.JTextField();
        CNama = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        Cdurasicuti = new javax.swing.JTextField();
        Keterangan = new javax.swing.JTextField();
        Next = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        muncul = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gerak = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(484, 426));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("NIP               :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 90, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nama            :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 140, 90, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Tanggal Cuti :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 90, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Durasi Cuti    :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 220, 100, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Keterangan   :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 260, 100, 17);

        Submit.setBackground(new java.awt.Color(51, 153, 255));
        Submit.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(130, 360, 90, 25);

        CNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNipActionPerformed(evt);
            }
        });
        getContentPane().add(CNip);
        CNip.setBounds(130, 100, 220, 30);
        getContentPane().add(CNama);
        CNama.setBounds(130, 140, 220, 30);

        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        getContentPane().add(tanggal);
        tanggal.setBounds(130, 180, 220, 30);

        Cdurasicuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CdurasicutiActionPerformed(evt);
            }
        });
        getContentPane().add(Cdurasicuti);
        Cdurasicuti.setBounds(130, 220, 220, 30);

        Keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeteranganActionPerformed(evt);
            }
        });
        getContentPane().add(Keterangan);
        Keterangan.setBounds(130, 260, 220, 90);

        Next.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Next.setText("Next ->");
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(420, 70, 50, 16);

        search.setBackground(new java.awt.Color(51, 153, 255));
        search.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(370, 100, 100, 30);

        muncul.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(muncul);
        muncul.setBounds(130, 60, 230, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("<- Kembali");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 70, 70, 17);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        gerak.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gerak.setText("                                ISILAH NIP TERLEBIH DAHULU, BARU BISA MENGISI DATA YANG LAIN!");
        jPanel1.add(gerak);
        gerak.setBounds(0, 0, 480, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\cuti.png")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 56, 480, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CdurasicutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CdurasicutiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CdurasicutiActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        Cuti c = new Cuti(CNip.getText(), CNama.getText(), tanggal.getText(), Cdurasicuti.getText(), Keterangan.getText());
        String nip = c.getNP();
        String nama = c.getNM();
        String date = c.getDaC();
        String durasi = c.getDuC();
        String keterangan = c.getK();
        
        try{
            String sql = " INSERT INTO datacuti VALUES('"+ nip + "','" + nama + "','" + date + "','" + durasi + "','" + keterangan + "')";
            java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil");
        } catch (HeadlessException |SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        mcuti mc = new mcuti();
        mc.close();
        DataCutiForm xx;
        xx = new DataCutiForm();
        xx.setVisible(true);
        this.dispose();
        DataCutiForm.AddRowJTable(new Object[]{
        CNip.getText(),CNama.getText(),
        tanggal.getText(),Cdurasicuti.getText(),
        Keterangan.getText(), 
        });
    }//GEN-LAST:event_SubmitActionPerformed

    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked
        mcuti mc = new mcuti();
        mc.close();
        DataCutiForm dc;
        dc = new DataCutiForm();
        dc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NextMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        Cuti c = new Cuti();
        String mncl = c.getP();
        if(CNip.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane, "Silahkan Cantumkan NIP Anda!");
        }else{
            String nip = CNip.getText();
            try{
                String sql = "SELECT `Nama` FROM `create` where NIP = '"+nip+"';";
                java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                ResultSet rs = pstm.executeQuery(sql);
                while (rs.next()){
                   CNama.setText(rs.getString("Nama"));
                }
                CNip.setEditable(true);
                CNama.setEditable(false);
                tanggal.setEditable(false);
                Cdurasicuti.setEditable(true);
                Keterangan.setEditable(true);
                Submit.setEnabled(true);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }
    }//GEN-LAST:event_searchActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        mcuti mc = new mcuti();
        mc.close();
        Aplikasi xx;
        xx = new Aplikasi();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void KeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeteranganActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void CNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CutiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CutiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CutiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CutiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CutiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNama;
    private javax.swing.JTextField CNip;
    private javax.swing.JTextField Cdurasicuti;
    private javax.swing.JTextField Keterangan;
    private javax.swing.JLabel Next;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel gerak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel muncul;
    private javax.swing.JButton search;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables
}
