/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasAkhir;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author herib
 */
public class DataKaryawan extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    private DefaultTableModel tabmode;

    static String a,b,c;
    public DataKaryawan() {
        initComponents();
        ActionListener acl=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                a = gerak.getText();
                b = a.substring(0,1);
                c = a.substring(1, a.length());
                gerak.setText(c+b);
            }
        };new javax.swing.Timer(300, acl).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        gerak = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tampilkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("DATA KARYAWAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 20, 325, 42);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("<-- KEMBALI");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 75, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 80);

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(null);

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Jabatan", "Tanggal Lahir", "Email", "No.Telepon", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(tabeldata);
        if (tabeldata.getColumnModel().getColumnCount() > 0) {
            tabeldata.getColumnModel().getColumn(0).setResizable(false);
            tabeldata.getColumnModel().getColumn(1).setResizable(false);
            tabeldata.getColumnModel().getColumn(2).setResizable(false);
            tabeldata.getColumnModel().getColumn(3).setResizable(false);
            tabeldata.getColumnModel().getColumn(4).setResizable(false);
            tabeldata.getColumnModel().getColumn(5).setResizable(false);
            tabeldata.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 123, 800, 352);

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));

        gerak.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gerak.setText("\"Bekerja bukan hanya untuk mencari materi. Bekerja adalah bermanfaat bagi orang banyak\" ~ Merry Riana                         ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("MOTIVASI KERJA : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(gerak)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(gerak)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 10, 800, 100);

        tampilkan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tampilkan.setText("Tampilkan Data");
        tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanActionPerformed(evt);
            }
        });
        jPanel2.add(tampilkan);
        tampilkan.setBounds(330, 490, 140, 27);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 800, 540);

        setSize(new java.awt.Dimension(799, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Aplikasi xx;
        xx = new Aplikasi();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void tampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanActionPerformed
        Object[]baris = {"NIP", "Nama", "Jabatan", "Tanggal Lahir", "Email", "No.Telepon", "Alamat"};
        tabmode = new DefaultTableModel(null, baris);
        tabeldata.setModel(tabmode);
        try{
            String sql = "SELECT * FROM `create` order by NIP asc ";
            java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            ResultSet hasil = pstm.executeQuery(sql);
            while (hasil.next()){
                String nip = hasil.getString("NIP");
                String nama = hasil.getString("Nama");
                String jbtn = hasil.getString("Jabatan");
                String tl = hasil.getString("Tanggal_Lahir");
                String e = hasil.getString("Email");
                String p = hasil.getString("Password");
                String telp = hasil.getString("No.Telepon");
                String a = hasil.getString("Alamat");
                String[] data = {nip, nama,jbtn, tl, e, telp, a};
                tabmode.addRow(data);
            }
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tampilkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gerak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabeldata;
    private javax.swing.JButton tampilkan;
    // End of variables declaration//GEN-END:variables
}
