/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasAkhir;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author herib
 */
public class DataCutiForm extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    String a,b,c;

    /**
     * Creates new form Cuti
     */
    public DataCutiForm() {
        initComponents();
        txtnip.setEditable(true);
        txtdurasicuti.setEditable(false);
        txtketerangan.setEditable(false);
        txtnama.setEditable(false);
        txttanggal.setEnabled(false);
        ActionListener acl=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                a = gerak.getText();
                b = a.substring(0,1);
                c = a.substring(1, a.length());
                gerak.setText(c+b);
            }
        };new javax.swing.Timer(300, acl).start();
    }
    private DefaultTableModel tabmode;
    private void Kosongkan_Form(){
        txtnip.setEditable(true);
        txtnip.setText(null);
        txtnama.setText(null);
        txttanggal.setDateFormatString(null);
        txtdurasicuti.setText(null);
        txtketerangan.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtketerangan = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtdurasicuti = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataCuti = new javax.swing.JTable();
        btsimpan = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnip = new javax.swing.JTextField();
        txttanggal = new com.toedter.calendar.JDateChooser();
        tampilkan = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        gerak = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(799, 620));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("NIP               :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 90, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Tanggal Cuti :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 90, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Durasi Cuti    :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 200, 100, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Keterangan   :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 90, 17);

        txtketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtketeranganActionPerformed(evt);
            }
        });
        getContentPane().add(txtketerangan);
        txtketerangan.setBounds(120, 250, 260, 80);
        getContentPane().add(txtnama);
        txtnama.setBounds(120, 100, 260, 30);

        txtdurasicuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdurasicutiActionPerformed(evt);
            }
        });
        getContentPane().add(txtdurasicuti);
        txtdurasicuti.setBounds(120, 200, 260, 30);

        TabelDataCuti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama", "Tanggal Cuti", "Durasi Cuti", "Keterangan"
            }
        ));
        TabelDataCuti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataCutiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDataCuti);
        if (TabelDataCuti.getColumnModel().getColumnCount() > 0) {
            TabelDataCuti.getColumnModel().getColumn(0).setResizable(false);
            TabelDataCuti.getColumnModel().getColumn(1).setResizable(false);
            TabelDataCuti.getColumnModel().getColumn(2).setResizable(false);
            TabelDataCuti.getColumnModel().getColumn(3).setResizable(false);
            TabelDataCuti.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 420, 790, 140);

        btsimpan.setText("SIMPAN");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btsimpan);
        btsimpan.setBounds(40, 350, 100, 25);

        bttambah.setText("TAMBAH");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        getContentPane().add(bttambah);
        bttambah.setBounds(470, 310, 100, 25);

        btedit.setText("EDIT");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        getContentPane().add(btedit);
        btedit.setBounds(150, 350, 100, 25);

        bthapus.setText("HAPUS");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        getContentPane().add(bthapus);
        bthapus.setBounds(260, 350, 100, 25);

        btkeluar.setText("KELUAR");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btkeluar);
        btkeluar.setBounds(470, 350, 100, 25);

        btbatal.setText("BATAL");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });
        getContentPane().add(btbatal);
        btbatal.setBounds(370, 350, 90, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\calender.png")); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(590, 0, 210, 420);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Nama            :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 100, 90, 17);
        getContentPane().add(txtnip);
        txtnip.setBounds(120, 52, 260, 30);
        getContentPane().add(txttanggal);
        txttanggal.setBounds(120, 150, 260, 30);

        tampilkan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tampilkan.setText("Refresh Table");
        tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanActionPerformed(evt);
            }
        });
        getContentPane().add(tampilkan);
        tampilkan.setBounds(330, 570, 140, 25);

        search.setBackground(new java.awt.Color(51, 153, 255));
        search.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(400, 50, 100, 30);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(null);

        gerak.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gerak.setText("                                                 DATA BISA TERISI JIKA TELAH MENGINPUTKAN NIP DAN MENEKAN TOMBOL \"SEARCH\" !!!");
        jPanel2.add(gerak);
        gerak.setBounds(7, 0, 805, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 590, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\datacuti.png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtketeranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtketeranganActionPerformed

    private void txtdurasicutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdurasicutiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdurasicutiActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        txtnip.setText("");
        txtnama.setText("");
        txtdurasicuti.setText("");
        txtketerangan.setText("");
        
        txtnip.setEditable(true);
        btsimpan.setEnabled(true);
        bthapus.setEnabled(false);
        btedit.setEnabled(false);
        btkeluar.setEnabled(true);
        btbatal.setEnabled(true);
        bttambah.setEnabled(true);
    }//GEN-LAST:event_bttambahActionPerformed

    private void TabelDataCutiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataCutiMouseClicked
        int row = TabelDataCuti.getSelectedRow();
        txtnip.setText(TabelDataCuti.getModel().getValueAt(row, 0).toString());
        txtnama.setText(TabelDataCuti.getModel().getValueAt(row, 1).toString());
        txtdurasicuti.setText(TabelDataCuti.getModel().getValueAt(row, 3).toString());
        txtketerangan.setText(TabelDataCuti.getModel().getValueAt(row, 4).toString());
        
        txtnip.setEditable(false);
        txttanggal.setEnabled(true);
        txtdurasicuti.setEditable(true);
        txtketerangan.setEditable(true);
        btsimpan.setEnabled(false);
        bthapus.setEnabled(true);
        btedit.setEnabled(true);
        btkeluar.setEnabled(true);
        btbatal.setEnabled(true);
        bttambah.setEnabled(true);
        
    }//GEN-LAST:event_TabelDataCutiMouseClicked

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        DataCuti dc = new DataCuti(txtnip.getText(), txtnama.getText(), txttanggal.getDateFormatString(), txtdurasicuti.getText(), txtketerangan.getText(),txttanggal.getDate());
        String nip = dc.getNP();
        String nama = dc.getNM();
        String date0 = dc.getDaC();
        Date date = dc.getT();
        String durasi = dc.getDuC();
        String keterangan = dc.getK();
        SimpleDateFormat dformat = new SimpleDateFormat("YYYY-MM-dd");
        String date1 = String.valueOf(dformat.format(date));
        
        if(nip.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan NIP Anda");
        }
        else if(nama.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan Nama");
        }
        else if(date.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan Tanggal Cuti");
        }
        else if(durasi.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan Durasi Cuti");
        }else{ 
            if(keterangan.equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Cantumkan Keterangan -> Alasan Anda Mengambil Cuti");     
        }
            try{
            String sql = " INSERT INTO datacuti VALUES('"+ nip + "','" + nama + "','" + date1 + "','" + durasi + "','" + keterangan + "')";
            java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil");
            
            Kosongkan_Form();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Proses Menyimpan Gagal!" +e);
        }
        }
        DefaultTableModel model = (DefaultTableModel) TabelDataCuti.getModel();
        model.addRow(new Object[]{nip,nama,date1,durasi,keterangan});
    }//GEN-LAST:event_btsimpanActionPerformed

    private void tampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanActionPerformed
        Object[]baris = {"NIP", "Nama", "Tanggal Cuti", "Durasi Cuti", "Keterangan"};
        tabmode = new DefaultTableModel(null, baris);
        TabelDataCuti.setModel(tabmode);
        try{
            String sql = "select * from datacuti order by NIP asc ";
            java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            ResultSet hasil = pstm.executeQuery(sql);
            while (hasil.next()){
                String nip = hasil.getString("NIP");
                String nama = hasil.getString("Nama");
                String tgl = hasil.getString("Tanggal_Cuti");
                String duc = hasil.getString("Durasi_Cuti");
                String ket = hasil.getString("Keterangan");
                String[] data = {nip, nama,tgl, duc, ket};
                tabmode.addRow(data);
            }
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        txtnip.setEditable(false);
        txtdurasicuti.setEditable(true);
        txtketerangan.setEditable(true);
        txtnama.setEditable(false);
        txttanggal.setEnabled(true);
        btsimpan.setEnabled(false);
    }//GEN-LAST:event_tampilkanActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        DataCuti dc = new DataCuti(txtnip.getText(), txtnama.getText(), txttanggal.getDateFormatString(), txtdurasicuti.getText(), txtketerangan.getText(),txttanggal.getDate());
        String nip = dc.getNP();
        String nama = dc.getNM();
        String date0 = dc.getDaC();
        Date date = dc.getT();
        String durasi = dc.getDuC();
        String keterangan = dc.getK();
        
        SimpleDateFormat dformat = new SimpleDateFormat("YYYY-MM-dd");
        String date1 = String.valueOf(dformat.format(date));
        try{
            String sql = "INSERT datacuti set NIP = '"+nip+"' , Nama = '"+nama+"' ,Tanggal_Cuti = '"+date1+"' , Durasi_Cuti = '"+durasi+"' ,Keterangan = '"+keterangan+"' On Duplicate Key Update NIP = '"+nip+"' , Nama = '"+nama+"' ,Tanggal_Cuti = '"+date1+"' , Durasi_Cuti = '"+durasi+"' ,Keterangan = '"+keterangan+"'";
            java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Edit Data Berhasil...");
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }         
            Kosongkan_Form();
    }//GEN-LAST:event_bteditActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        Kosongkan_Form();
    }//GEN-LAST:event_btbatalActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        Aplikasi xx;
        xx = new Aplikasi();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btkeluarActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
         try{
            String sql = "DELETE FROM datacuti WHERE NIP='" + txtnip.getText() + "'";
                    java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.execute();
                    JOptionPane.showMessageDialog(null, "Hapus Data Berhasil...");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Kosongkan_Form();
        txtnip.setEditable(true);
        txtdurasicuti.setEditable(false);
        txtketerangan.setEditable(false);
        txtnama.setEditable(false);
        txttanggal.setEnabled(false);
    }//GEN-LAST:event_bthapusActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        DataCuti dc = new DataCuti();
        String mncl = dc.getP();
        if(txtnip.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Silahkan Cantumkan NIP Anda!");
        }else{
            String nip = txtnip.getText();
            try{
                String sql = "SELECT `Nama` FROM `create` where NIP = '"+nip+"';";
                java.sql.Connection conn = (Connection) AbsensiPegawai.getConnection();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                ResultSet rs = pstm.executeQuery(sql);
                while (rs.next()){
                    txtnama.setText(rs.getString("Nama"));
                }
                txtnama.setEditable(false);
                txtnip.setEditable(true);
                txtdurasicuti.setEditable(true);
                txtketerangan.setEditable(true);
                txttanggal.setEnabled(true);
                
                btsimpan.setEnabled(true);
                bthapus.setEnabled(true);
                btedit.setEnabled(true);
                btkeluar.setEnabled(true);
                btbatal.setEnabled(true);
                bttambah.setEnabled(true);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_searchActionPerformed
    public static void AddRowJTable(Object[] dataRow){
        DefaultTableModel model = (DefaultTableModel)TabelDataCuti.getModel();
        model.addRow(dataRow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataCutiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataCutiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataCutiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataCutiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataCutiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable TabelDataCuti;
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton bttambah;
    private javax.swing.JLabel gerak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JButton tampilkan;
    private javax.swing.JTextField txtdurasicuti;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private com.toedter.calendar.JDateChooser txttanggal;
    // End of variables declaration//GEN-END:variables
}
