/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasAkhir;

import javax.swing.JFrame;
import TugasAkhir.CreatForm;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author herib
 */

public class Login extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);//bentuk tengah di layar
        showOnScreen(0, this);
    }
    
    public static void showOnScreen(int screen, JFrame frame){
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] gd = ge.getScreenDevices();
        if(screen > -1 && screen < gd.length){
            frame.setLocation(gd[screen].getDefaultConfiguration().getBounds().x, frame.getY());
        }else if(gd.length > 0){
            frame.setLocation(gd[0].getDefaultConfiguration().getBounds().x, frame.getY());
        }else{
            throw new RuntimeException("No Screens Found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sigin = new javax.swing.JButton();
        email1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2Creat = new javax.swing.JLabel();
        jButton2minimize = new javax.swing.JButton();
        jButton2Close1 = new javax.swing.JButton();
        salah1 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setUndecorated(true);
        setSize(new java.awt.Dimension(680, 566));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setText("Email       :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 130, 70, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 170, 80, 30);

        sigin.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        sigin.setText("SIGN IN");
        sigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siginActionPerformed(evt);
            }
        });
        getContentPane().add(sigin);
        sigin.setBounds(320, 250, 270, 25);

        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        getContentPane().add(email1);
        email1.setBounds(370, 130, 220, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("LOGIN");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 80, 90, 40);

        jLabel2Creat.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2Creat.setText("Click here to creat new account?");
        jLabel2Creat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Creat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2CreatMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2Creat);
        jLabel2Creat.setBounds(360, 280, 230, 19);

        jButton2minimize.setBackground(new java.awt.Color(255, 0, 0));
        jButton2minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2minimize.setText("-");
        jButton2minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jButton2minimize);
        jButton2minimize.setBounds(510, 0, 50, 40);

        jButton2Close1.setBackground(new java.awt.Color(255, 0, 0));
        jButton2Close1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2Close1.setText("X");
        jButton2Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2Close1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2Close1);
        jButton2Close1.setBounds(560, 0, 50, 40);

        salah1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salah1.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(salah1);
        salah1.setBounds(330, 210, 260, 30);
        getContentPane().add(jPasswordField);
        jPasswordField.setBounds(370, 170, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\herib\\OneDrive\\Documents\\NetBeansProjects\\semester 2\\src\\TugasAkhir\\images\\login (1) (2).png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 390);

        setSize(new java.awt.Dimension(612, 392));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    private void jButton2minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2minimizeMouseClicked

    private void jButton2Close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2Close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton2Close1MouseClicked

    private void jLabel2CreatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2CreatMouseClicked
        CreatForm cr = new CreatForm();
        cr.setVisible(true);
        cr.pack();
        cr.setLocationRelativeTo(null);
        cr.setDefaultCloseOperation(CreatForm.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel2CreatMouseClicked

    private void siginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siginActionPerformed
        PreparedStatement ps;
        ResultSet rs;
        String email = email1.getText();
        String pass = String.valueOf(jPasswordField.getPassword());
        
        String query="SELECT * FROM `create` WHERE `Email` =? AND `Password` =?";
        
        try{
            ps = AbsensiPegawai.getConnection().prepareStatement(query);
            
            ps.setString(1, email);
            ps.setString(2, pass);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                Aplikasi a = new Aplikasi();
                a.setVisible(true);
                a.pack();
                a.setLocationRelativeTo(null);
                this.dispose();
                Aplikasi.x1.setText(rs.getString(2));
                Aplikasi.y1.setText(rs.getString(5));
                Aplikasi.selamatdatang.setText("            SELAMAT DATANG "+rs.getString(2)+ " JIKA KAMU YAKIN MEWUJUDKAN SEBUAH MIMPI, SEBENARNYA KAMU SUDAH SEPARUH JALAN UNTUK MEWUJUDKANNYA");
            }else{
                JOptionPane.showMessageDialog(null, "Username/Password Salah Atau Akun Belum Terdaftar");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_siginActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email1;
    private javax.swing.JButton jButton2Close1;
    private javax.swing.JButton jButton2minimize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Creat;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel salah1;
    private javax.swing.JButton sigin;
    // End of variables declaration//GEN-END:variables
}
